export const BAG_LIST_REQUEST = 'BAG_LIST_REQUEST';
export const BAG_LIST_SUCCESS = 'BAG_LIST_SUCCESS';
export const BAG_LIST_FAIL = 'BAG_LIST_FAIL';

export const BAG_DETAILS_REQUEST = 'BAG_DETAILS_REQUEST';
export const BAG_DETAILS_SUCCESS = 'BAG_DETAILS_SUCCESS';
export const BAG_DETAILS_FAIL = 'BAG_DETAILS_FAIL';