export const BUCKET_LIST_REQUEST = 'BUCKET_LIST_REQUEST';
export const BUCKET_LIST_SUCCESS = 'BUCKET_LIST_SUCCESS';
export const BUCKET_LIST_FAIL = 'BUCKET_LIST_FAIL';

export const BUCKET_DETAILS_REQUEST = 'BUCKET_DETAILS_REQUEST';
export const BUCKET_DETAILS_SUCCESS = 'BUCKET_DETAILS_SUCCESS';
export const BUCKET_DETAILS_FAIL = 'BUCKET_DETAILS_FAIL';