export const GNG_LIST_REQUEST = 'GNG_LIST_REQUEST';
export const GNG_LIST_SUCCESS = 'GNG_LIST_SUCCESS';
export const GNG_LIST_FAIL = 'GNG_LIST_FAIL';

export const GNG_DETAILS_REQUEST = 'GNG_DETAILS_REQUEST';
export const GNG_DETAILS_SUCCESS = 'GNG_DETAILS_SUCCESS';
export const GNG_DETAILS_FAIL = 'GNG_DETAILS_FAIL';