export const ONEG_LIST_REQUEST = 'ONEG_LIST_REQUEST';
export const ONEG_LIST_SUCCESS = 'ONEG_LIST_SUCCESS';
export const ONEG_LIST_FAIL = 'ONEG_LIST_FAIL';


export const ONEG_DETAILS_REQUEST = 'ONEG_DETAILS_REQUEST';
export const ONEG_DETAILS_SUCCESS = 'ONEG_DETAILS_SUCCESS';
export const ONEG_DETAILS_FAIL = 'ONEG_DETAILS_FAIL';