export const SPORTSTIN_LIST_REQUEST = 'SPORTSTIN_LIST_REQUEST';
export const SPORTSTIN_LIST_SUCCESS = 'SPORTSTIN_LIST_SUCCESS';
export const SPORTSTIN_LIST_FAIL = 'SPORTSTIN_LIST_FAIL';

export const SPORTSTIN_DETAILS_REQUEST = 'SPORTSTIN_DETAILS_REQUEST';
export const SPORTSTIN_DETAILS_SUCCESS = 'SPORTSTIN_DETAILS_SUCCESS';
export const SPORTSTIN_DETAILS_FAIL = 'SPORTSTIN_DETAILS_FAIL';