export const THREEG_LIST_REQUEST = 'THREEG_LIST_REQUEST';
export const THREEG_LIST_SUCCESS = 'THREEG_LIST_SUCCESS';
export const THREEG_LIST_FAIL = 'THREEG_LIST_FAIL';

export const THREEG_DETAILS_REQUEST = 'THREEG_DETAILS_REQUEST';
export const THREEG_DETAILS_SUCCESS = 'THREEG_DETAILS_SUCCESS';
export const THREEG_DETAILS_FAIL = 'THREEG_DETAILS_FAIL';