export const TWOG_LIST_REQUEST = 'TWOG_LIST_REQUEST';
export const TWOG_LIST_SUCCESS = 'TWOG_LIST_SUCCESS';
export const TWOG_LIST_FAIL = 'TWOG_LIST_FAIL';

export const TWOG_DETAILS_REQUEST = 'TWOG_DETAILS_REQUEST';
export const TWOG_DETAILS_SUCCESS = 'TWOG_DETAILS_SUCCESS';
export const TWOG_DETAILS_FAIL = 'TWOG_DETAILS_FAIL';