const bagdata = {
    bag: [
        {
            _id:'1',
            name: 'cheese',
            image:'/public/Cheddar-popcorn.jpg',
            price: '$6.25',
            sizes: 'SM',  
        },
        {
            _id:'2',
            name: 'cheese',
            image:'/public/Cheddar-popcorn.jpg',
            price: '$8.25',
            sizes: 'MD',  
        },
        {
            _id:'3',
            name: 'cheese',
            image:'/public/Cheddar-popcorn.jpg',
            price: '$10.50',
            sizes: 'LG',  
        },
        {
            _id:'4',
            name: 'cheese',
            image:'/public/Cheddar-popcorn.jpg',
            price: '$13.00',
            sizes: 'XL',  
        },
        {
            _id:'5',
            name: 'caramel',
            image:'/public/caramel.jpeg',
            price: '$6.75',
            sizes: 'SM',  
        },
        {
            _id:'6',
            name: 'caramel',
            image:'/public/caramel.jpeg',
            price: '$9.50',
            sizes: 'MD',  
        },
        {
            _id:'7',
            name: 'caramel',
            image:'/public/caramel.jpeg',
            price: '$14.50',
            sizes: 'LG',  
        },
        {
            _id:'8',
            name: 'caramel',
            image:'/public/caramel.jpeg',
            price: '$16.75',
            sizes: 'XL',  
        },
        {
            _id:'9',
            name: 'cheesy caramel',
            image:'/public/Mix.jpg',
            price: '$7.25',
            sizes: 'SM',  
        },
        {
            _id:'10',
            name: 'cheesy caramel',
            image:'/public/Mix.jpg',
            price: '$10.00',
            sizes: 'MD',  
        },
        {
            _id:'11',
            name: 'cheesy caramel',
            image:'/public/Mix.jpg',
            price: '$14.50',
            sizes: 'LG',  
        },
        {
            _id:'12',
            name: 'cheesy caramel',
            image:'/public/Mix.jpg',
            price: '$18.00',
            sizes: 'XL',  
        },
        {
            _id:'13',
            name: 'cheese',
            image:'/public/Sm-bag.jpg',
            price: '$7.75',
            sizes: 'SM',  
        },
        {
            _id:'14',
            name: 'cheese',
            image:'/public/Sm-bag.jpg',
            price: '$10.50',
            sizes: 'MD',  
        },
        {
            _id:'15',
            name: 'cheese',
            image:'/public/Sm-bag.jpg',
            price: '$14.50',
            sizes: 'LG',  
        },
        {
            _id:'16',
            name: 'cheese',
            image:'/public/Sm-bag.jpg',
            price:'$18.00',
            sizes: 'XL',  
        }

    ]}
export default bagdata;